[pytest]
markers =
    smoke: Các test case quan trọng (critical path)
    regression: Toàn bộ test case hồi quy
    login: Các test liên quan đến đăng nhập
    search: Các test liên quan đến tìm kiếm
    payment: Các test về thanh toán