from playwright.sync_api import Page, sync_playwright, expect
import re

def test_crm_page(page: Page):

    page.goto("https://crm.anhtester.com/admin/authentication")
    page.get_by_label("Email Address").fill("admin@example.com")
    page.get_by_label("Password").fill("123456")
    page.get_by_role("button", name="Login").click()

    logo = page.locator("//div[@id='logo']/descendant::img[contains(@alt,'Perfex CRM')]")

    dashboard_menu = page.locator("//span[normalize-space()='Dashboard']")
    customer_menu = page.locator("//span[normalize-space()='Customer']")
    sales_menu = page.locator("//span[normalize-space()='Sales']")
    subscriptions_menu = page.locator("//span[normalize-space()='Subscriptions']")
    expenses_menu = page.locator("//span[normalize-space()='Expenses']")
    contracts_menu = page.locator("//span[normalize-space()='Contracts']")
    projects_menu = page.locator("//span[normalize-space()='Projects']")
    tasks_menu = page.locator("//span[normalize-space()='Tasks']")
    support_menu = page.locator("//span[normalize-space()='Support']")
    leads_menu = page.locator("//span[normalize-space()='Leads']")
    estimate_request_menu = page.locator("//span[normalize-space()='Estimate Request']")
    knowledge_base = page.locator("//span[normalize-space()='Knowledge Base']")
    utilities_menu = page.locator("//span[normalize-space()='Utilities']")
    reports_menu = page.locator("//span[normalize-space()='Reports']")

    dashboard_icon = page.locator("//span[normalize-space()='Dashboard']/preceding-sibling::i")
    customers_icon = page.locator("//span[normalize-space()='Customers']/preceding-sibling::i")
    sales_icon = page.locator("//span[normalize-space()='Sales']/preceding-sibling::i")
    subscriptions_icon = page.locator("//span[normalize-space()='Subscriptions']/preceding-sibling::i")
    expenses_icon = page.locator("//span[normalize-space()='Expenses']/preceding-sibling::i")
    contracts_icon = page.locator("//span[normalize-space()='Contracts']/preceding-sibling::i")
    projects_icon = page.locator("//span[normalize-space()='Projects']/preceding-sibling::i")
    tasks_icon = page.locator("//span[normalize-space()='Tasks']/preceding-sibling::i")
    support_icon = page.locator("//span[normalize-space()='Support']/preceding-sibling::i")
    leads_icon = page.locator("//span[normalize-space()='Leads']/preceding-sibling::i")
    estimate_request_icon = page.locator("//span[normalize-space()='Estimate Request']/preceding-sibling::i")
    knowledge_base_icon = page.locator("//span[normalize-space()='Knowledge Base']/preceding-sibling::i")
    utilities_icon = page.locator("//span[normalize-space()='Utilities']/preceding-sibling::i")
    reports_icon = page.locator("//span[normalize-space()='Reports']/preceding-sibling::i")

    sales_arrow = page.locator("//span[normalize-space()='Sales']/following-sibling::*")
    utilities_arrow = page.locator("//span[normalize-space()='Utilities']/following-sibling::*")
    reports_arrow = page.locator("//span[normalize-space()='Reports']/following-sibling::*")

    proposals_submenu = page.locator("//ul[contains(@class,'nav-second-level')]/descendant::span[normalize-space()='Proposals']")
    estimates_submenu = page.locator("//ul[contains(@class,'nav-second-level')]/descendant::span[normalize-space()='Estimates']")
    invoices_submenu = page.locator("//ul[contains(@class,'nav-second-level')]/descendant::span[normalize-space()='Invoices']")
    payments_submenu = page.locator("//ul[contains(@class,'nav-second-level')]/descendant::span[normalize-space()='Payments']")
    credit_notes_submenu = page.locator("//ul[contains(@class,'nav-second-level')]/descendant::span[normalize-space()='Credit Notes']")
    items_submenu = page.locator("//ul[contains(@class,'nav-second-level')]/descendant::span[normalize-space()='Items']")
    media_submenu = page.locator("//ul[contains(@class,'nav-second-level')]/descendant::span[normalize-space()='Media']")
    bulk_PDF_export_submenu = page.locator("//ul[contains(@class,'nav-second-level')]/descendant::span[normalize-space()='Bulk PDF Export']")
    calendar_submenu = page.locator("//ul[contains(@class,'nav-second-level')]/descendant::span[normalize-space()='Calendar']")
    sales_submenu = page.locator("//ul[contains(@class,'nav-second-level')]/descendant::span[normalize-space()='Sales']")
    expenses_submenu = page.locator("//ul[contains(@class,'nav-second-level')]/descendant::span[normalize-space()='Expenses']")
    expenses_vs_income_submenu = page.locator("//ul[contains(@class,'nav-second-level')]/descendant::span[normalize-space()='Expenses vs Income']")
    leads_submenu = page.locator("//ul[contains(@class,'nav-second-level')]/descendant::span[normalize-space()='Leads']")
    timesheets_overview_submenu = page.locator("//ul[contains(@class,'nav-second-level')]/descendant::span[normalize-space()='Timesheets overview']")
    KB_articles_submenu = page.locator("//ul[contains(@class,'nav-second-level')]/descendant::span[normalize-space()='KB Articles']")

    share_icon = page.locator("//a[@class='open_newsfeed desktop']/child::*[local-name()='svg']")
    checkmark_icon = page.locator("//a[@href='https://crm.anhtester.com/admin/todo']/child::*[local-name()='svg']")
    human_img = page.locator("//a[@href='#']//img[@src='https://crm.anhtester.com/assets/images/user-placeholder.jpg']")
    clock_icon = page.locator("//li[@class='icon header-timers timer-button tw-relative ltr:tw-mr-1.5 rtl:tw-ml-1.5']//a[@href='#']//*[local-name()='svg']")
    bell_icon = page.locator("//li[@title='Notifications']//*[local-name()='svg']")

    LHS_menu_icon = page.locator("//div[@id='header']/descendant::i")
    searchbar = page.locator("//div[@id='top_search']/child::input")
    search_button = page.locator("//div[@id='top_search_button']")
    add_button = page.locator("//ul[@class='nav navbar-nav visible-md visible-lg']/descendant::span")